version: '3'
#Serviço node para rodar a API configurações dentro do da pasta src
services:
  GreenAPI:
    image: node
    build: ./Greenapi
    depends_on:
      - greenDb
    networks:
      - green
    ports:
      - 3000:3000
# Banco de dados com as tabelas de Boletos e lotes
  greenDb:
    container_name: green_Db
    environment:            
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./dump:/docker-entrypoint-initdb.d     
    image: mysql
    networks:
      - green
      
networks:
  green:
    driver: bridge