version: '3'
services:
  GreenAPI:
    image: node
    build: ./Greenapi
    depends_on:
      - greenDb
    networks:
      - green
    ports:
      - 3000:3000

  greenDb:
    container_name: green_Db
    environment:            
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./dump:/docker-entrypoint-initdb.d     
    image: mysql
    ports: 
      - "3306:3306"
    networks:
      - green

networks:
  green:
    driver: bridge